# Generated by Django 6.1.1 on 2026-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
